name: wake-api-test

on:
  push:
    path-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # $WIT_WORKSPACE path is relative to $GITHUB_WORKSPACE
      WIT_WORKSPACE: wit-workspace

    steps:
      - uses: actions/checkout@v2
        with:
          path: wit-packages/cmsis-svd-generator

      - name: 'Init Wit Workspace'
        uses: sifive/wit/actions/wit@v0.12.0
        with:
          command: init
          arguments: |
            ${{ env.WIT_WORKSPACE }}
            -a ./wit-packages/cmsis-svd-generator
            -a git@github.com:sifive/environment-blockci-sifive.git::0.3.0
          force_github_https: true

      - name: 'Run Wake API Test'
        run: |
          set -euo pipefail
          docker run \
            --volume="$GITHUB_WORKSPACE/$WIT_WORKSPACE:/mnt/workspace" \
            --workdir="/mnt/workspace" \
            --rm \
            sifive/environment-blockci:0.3.0 \
            cmsis-svd-generator/tests/test-wake-api.sh

      - name: 'Run generator install test'
        run: |
          set -euo pipefail
          docker run \
            --volume="$GITHUB_WORKSPACE/$WIT_WORKSPACE:/mnt/workspace" \
            --workdir="/mnt/workspace" \
            --rm \
            sifive/environment-blockci:0.3.0 \
            cmsis-svd-generator/tests/test-wake-install.sh
